name: Remind running Slow CI

on:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  remind:
    name: remind
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install requirements
      run: |
        echo "Bonjour"

    - name: Find remind comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ github.event.number }}
        body-includes: Slow CI

    - name: Add remind comment if not present
      uses: thollander/actions-comment-pull-request@v2
      if: steps.find_comment.outputs.comment-id == ''

      with:
        message: 'This PR has no Slow CI triggered yet. Please trigger it and make sure all tests passing before merge.'
        pr_number: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.comment_bot_token }}

    - name: Write a comment that will be deleted at the end of the job
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          The PR is being built...
        comment_tag: to_delete
        mode: delete
        pr_number: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.comment_bot_token }}
