name: Remind running Slow CI

on:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  remind:
    name: remind
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install requirements
      run: |
        echo "Bonjour"

    - name: Find comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ github.event.number }}
        body-includes: Slow CI

    - run: |
        echo ${{ steps.find_comment.outputs.comment-id }}

    - name: delete previous comment (if found)
      if: steps.find_comment.outputs.comment-id != ''
      uses: actions/github-script@v6
      with:
        result-encoding: string
        github-token: ${{ secrets.comment_bot_token }}
        script: |
          github.rest.issues.deleteComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ steps.find_comment.outputs.comment-id }},
          })

    - name: Add remind comment
      uses: thollander/actions-comment-pull-request@v2
      # if: steps.find_comment.outputs.comment-id == ''
      with:
        message: 'This PR has no Slow CI triggered yet. Please trigger it and make sure all tests passing before merge.'
        pr_number: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.comment_bot_token }}
